meshtasticd syslog wrapper

diff --git a/package/meshtasticd/S99meshtasticd b/package/meshtasticd/S99meshtasticd
--- a/package/meshtasticd/S99meshtasticd
+++ b/package/meshtasticd/S99meshtasticd
@@ -1,15 +1,33 @@
 #!/bin/sh
 #
 # Starts the meshtasticd daemon.
+# Inspired by:
+# https://github.com/buildroot/buildroot/blob/master/package/docker-engine/S60dockerd
 #
 
 NAME=meshtasticd
 DAEMON=/usr/sbin/$NAME
 PIDFILE=/var/run/$NAME.pid
 
+MESHTATICD_ARGS=""
+
 start() {
 	printf "Starting $NAME: "
-	start-stop-daemon -S -q -m -b -p $PIDFILE --exec $DAEMON && echo "OK" || echo "Failed"
+	# Meshtasticd logs only to stdout/stderr, which is lost with
+	# --background. The wrapper script runs the given command
+	# (after "--", including meshtasticd) and forwards stdout/stderr
+	# to syslog.
+	# shellcheck disable=SC2086 # we need word splitting for MESHTASTICD_ARGS
+	start-stop-daemon --start --background --pidfile "$PIDFILE" \
+		--exec /usr/libexec/meshtasticd-syslog-wrapper.sh \
+		-- "$DAEMON" $MESHTATICD_ARGS
+	status=$?
+	if [ "$status" -eq 0 ]; then
+		echo "OK"
+	else
+		echo "FAIL"
+	fi
+	return "$status"
 }
 stop() {
 	printf "Stopping $NAME: "
@@ -18,6 +36,7 @@ stop() {
 }
 restart() {
 	stop
+	sleep 1
 	start
 }
 
