Add `status` case for init.d

diff --git a/package/meshtasticd/S99meshtasticd b/package/meshtasticd/S99meshtasticd
--- a/package/meshtasticd/S99meshtasticd
+++ b/package/meshtasticd/S99meshtasticd
@@ -8,32 +8,46 @@ DAEMON=/usr/sbin/$NAME
 PIDFILE=/var/run/$NAME.pid
 
 start() {
-        printf "Starting $NAME: "
-        start-stop-daemon -S -q -p $PIDFILE --exec $DAEMON && echo "OK" || echo "Failed"
+	printf "Starting $NAME: "
+	start-stop-daemon -S -q -p $PIDFILE --exec $DAEMON && echo "OK" || echo "Failed"
 }
 stop() {
-        printf "Stopping $NAME: "
-        start-stop-daemon -K -q -p $PIDFILE && echo "OK" || echo "Failed"
-        rm -f $PIDFILE
+	printf "Stopping $NAME: "
+	start-stop-daemon -K -q -p $PIDFILE && echo "OK" || echo "Failed"
+	rm -f $PIDFILE
+}
+status() {
+	if [ -f "$PIDFILE" ]; then
+		if ps -p $(cat $PIDFILE) > /dev/null 2>&1; then
+			echo "$NAME is running (PID: $(cat $PIDFILE))"
+		else
+			echo "$NAME is not running, but PID file exists"
+		fi
+	else
+		echo "$NAME is not running"
+	fi
 }
 restart() {
-        stop
-        start
+	stop
+	start
 }
 
 case "$1" in
-  start)
-        start
-        ;;
-  stop)
-        stop
-        ;;
-  restart|reload)
-        restart
-        ;;
-  *)
-        echo "Usage: $0 {start|stop|restart}"
-        exit 1
+	start)
+		start
+		;;
+	stop)
+		stop
+		;;
+	status)
+		status
+		;;
+	restart|reload)
+		restart
+		;;
+	*)
+		echo "Usage: $0 {start|stop|status|restart}"
+		exit 1
 esac
 
 exit $?
